name: Python App Build template

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial step to pull Common Build tool script
        run: |
          ls -la
          pwd
          echo Start the curl command  

