name: Python App Build template

on:
  push:
    branches: [ main ]
    
env:
  AFAAS_DOCKER_REGISTRY: ${{ secrets.AFAAS_DOCKER_REGISTRY }}
  AFAAS_USER: ${{ secrets.AFAAS_USER }}
  AFAAS_TOKEN: ${{ secrets.AFAAS_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial step to pull Common Build tool script
        run: |
          ls -la
          pwd
          echo ENV VARIABLES
          echo $AFAAS_DOCKER_REGISTRY
          echo AFAAS_USER $AFAAS_USER
          echo AFAAS_TOKEN $AFAAS_TOKEN
          echo Start the curl command version
          curl --version
          echo Runnin get command
          curl -s -u '${{ secrets.AFAAS_USER }}:${{ secrets.AFAAS_TOKEN }}' -X GET 'https://${{ secrets.AFAAS_DOCKER_REGISTRY }}/ibmcb-generic-local/BuildTools/get_build_tools.sh'

